package com.example.restfulwebservices.model;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;

@Entity
@Table(name = "USER")
public class User {
	
	/**
	 * @Id denotes that this property will be primary key.
	 * @GeneratedValue denoted that this property value will be autogenerated.
	 * 
	 * **/
	@Id
	@GeneratedValue
	private Integer id;
	
	@Size(min=3, message="Name should have atleast 3 characters")
	private String name;
	
	/**
	 * we pass the property name on which @ManyToOne is set
	 * which in our case is the user property on class Post
	 * **/ 
	@OneToMany(mappedBy = "user", fetch = FetchType.LAZY)
	private List<Post> posts;
	
	public User() {}
	
	public User(int id, String name) {
		this.id = id;
		this.name = name;
	}
	
	public User(String name) {
		this.name = name;
	}
	
	public Integer getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

	public List<Post> getPosts() {
		return posts;
	}

	public void setPosts(List<Post> posts) {
		this.posts = posts;
	}
}
